# Generated by Django 4.0.2 on 2022-03-15 07:48

from django.db import migrations, models
import parler


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='photos/about', verbose_name='Main Image')),
                ('image_1', models.ImageField(upload_to='photos/about', verbose_name='Image 1')),
                ('image_2', models.ImageField(upload_to='photos/about', verbose_name='Image 2')),
                ('image_3', models.ImageField(upload_to='photos/about', verbose_name='Image 3')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
	    bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
    ]
