# Generated by Django 4.0.2 on 2022-03-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_aboutimages'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutimages',
            options={'verbose_name': 'About Image', 'verbose_name_plural': 'About Image'},
        ),
    ]
