# Generated by Django 4.0.2 on 2022-03-17 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_aboutimages_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='photos/about', verbose_name='Image 1')),
                ('url', models.CharField(max_length=250, verbose_name='Link')),
            ],
            options={
                'verbose_name': 'Partners',
                'verbose_name_plural': 'Partners',
            },
        ),
    ]
