# Generated by Django 4.0.2 on 2022-03-17 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_partners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partners',
            name='url',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Link'),
        ),
    ]
