# Generated by Django 4.0.2 on 2022-03-14 12:34

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image', models.ImageField(upload_to='photos/products', verbose_name='Images')),
                ('is_available', models.BooleanField(default=True, verbose_name='Is Available')),
                ('top', models.BooleanField(default=False, verbose_name='Top')),
                ('brand', models.BooleanField(default=False, verbose_name='Brand')),
                ('v_nalichi', models.BooleanField(default=True, verbose_name='V nalichii')),
                ('cena_po_zaprosu', models.BooleanField(default=False, verbose_name='Price po zaprosu')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('modified_date', models.DateTimeField(auto_now=True, verbose_name='Modified Date')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('product_name', models.CharField(max_length=200, unique=True, verbose_name='Product Name')),
                ('description', models.TextField(blank=True, max_length=1500, verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=330, verbose_name='Short Description')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='store.product')),
            ],
            options={
                'verbose_name': 'Product Translation',
                'db_table': 'store_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
