# Generated by Django 4.0.2 on 2022-04-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaWords',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.CharField(max_length=255, verbose_name='meta')),
            ],
            options={
                'verbose_name': 'Meta Word',
                'verbose_name_plural': 'Meta Words',
            },
        ),
    ]
