# Generated by Django 4.0.2 on 2022-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_product_meta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='meta',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Meta'),
        ),
    ]
