# Generated by Django 4.0.2 on 2022-05-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
