# Generated by Django 3.2 on 2022-11-08 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_metadetails'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MetaDetails',
            new_name='MetaDetail',
        ),
    ]
